settings:
  isr_names_modifiers:
    - callback
    - Handler

  isr_var_types_exceptions:
    - SemaphoreHandle_t
    - TimerHandle_t
    - QueueHandle_t

  isr_config_callback:
    - gpio_set_irq_enabled_with_callback

rule_1_2:
  id: notVolatileVarISR
  msg:
    All global variables that are accessed from ISR must be declared as volatile to ensure that the compiler will not optimize it out.

rule_1_3:
  id: wrongUseOfVolatile
  msg: Local variables should not be declared as volatile to ensure that the compiler will optimize it out.

rule_1_4:
  id: wrongUseOfGlobalVar
  msg: Global variables should generally be avoided, except when necessary or when dealing with IRQs.
  exceptions:
    - SemaphoreHandle_t
    - TimerHandle_t
    - QueueHandle_t
